[metadata]
name = "rose-pine"
origin_url = "https://github.com/dhruvinsh/dotfiles"

# rose-pine color pallet
# Role          |Hex    |RGB               |HSL
# Base          |#191724|rgb(25, 23, 36)   |hsl(249deg, 22%, 12%)
# Surface       |#1f1d2e|rgb(31, 29, 46)   |hsl(247deg, 23%, 15%)
# Overlay       |#26233a|rgb(38, 35, 58)   |hsl(248deg, 25%, 18%)
# Muted         |#6e6a86|rgb(110, 106, 134)|hsl(249deg, 12%, 47%)
# Subtle        |#908caa|rgb(144, 140, 170)|hsl(248deg, 15%, 61%)
# Text          |#e0def4|rgb(224, 222, 244)|hsl(245deg, 50%, 91%)
# Love          |#eb6f92|rgb(235, 111, 146)|hsl(343deg, 76%, 68%)
# Gold          |#f6c177|rgb(246, 193, 119)|hsl(35deg, 88%, 72%)
# Rose          |#ebbcba|rgb(235, 188, 186)|hsl(2deg, 55%, 83%)
# Pine          |#31748f|rgb(49, 116, 143) |hsl(197deg, 49%, 38%)
# Foam          |#9ccfd8|rgb(156, 207, 216)|hsl(189deg, 43%, 73%)
# Iris          |#c4a7e7|rgb(196, 167, 231)|hsl(267deg, 57%, 78%)
# Highlight Low |#21202e|rgb(33, 32, 46)   |hsl(244deg, 18%, 15%)
# Highlight Med |#403d52|rgb(64, 61, 82)   |hsl(249deg, 15%, 28%)
# Highlight High|#524f67|rgb(82, 79, 103)  |hsl(248deg, 13%, 36%)

[colors]
foreground = "#e0def4"
background = "#191724"

compose_cursor = "#ebbcba" # pending leader key color
cursor_bg = "#e0def4"
cursor_fg = "#524f67"
cursor_border = "#e0def4"

# selection_bg = "#2a283e"
selection_bg = "#403d52" # highlight-mid
selection_fg = "#e0def4"

scrollbar_thumb = "#6e6a86"
split = "#908caa"
visual_bell = "#524f67"

ansi = [
  "#26233a",
  "#eb6f92",
  "#31748f",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",
]
brights = [
  "#6e6a86",
  "#eb6f92",
  "#31748f",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",
]

[colors.indexed]
16 = "#fab387"
17 = "#f5e0dc"

# this only applies to retro tab bar
# see: https://wezfurlong.org/wezterm/config/appearance.html
[colors.tab_bar]
background = "#191724"
inactive_tab_edge = "#232831"
inactive_tab_edge_hover = "#39404f"

[colors.tab_bar.active_tab]
bg_color = "#26233a"
fg_color = "#e0def4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#191724"
fg_color = "#6e6a86"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#26233a"
fg_color = "#e0def4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#191724"
fg_color = "#6e6a86"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#26233a"
fg_color = "#e0def4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
